
def build_location_payload(
    program_id=None,
    name="Update The Name",
    company=None,
    shipping_reference=None,
    geofence_radius_departure=None,
    geofence_radius_arrival=None,
    required_data_points_departure=None,
    required_data_points_arrival=None,
    type_id=None,
    data_point_sequence_departure_id=None,
    data_point_sequence_arrival_id=None,
    time_zone=None,
    address1=None,
    address2=None,
    city=None,
    state=None,
    zip_code=None,
    country=None,
    latitude=None,
    longitude=None,
    location_group_ids=None,
    product_ids=None,
    location_segment_name=None
):
    return {
        "programId": program_id,
        "name": name,
        "company": company,
        "shippingReference": shipping_reference,
        "geofenceRadiusDeparture": geofence_radius_departure or 5,
        "geofenceRadiusArrival": geofence_radius_arrival or 5,
        "requiredDataPointsDeparture": required_data_points_departure or 3,
        "requiredDataPointsArrival": required_data_points_arrival or 1 ,
        "typeId": type_id or "3",
        "dataPointSequenceDepartureId": data_point_sequence_departure_id or 1,
        "dataPointSequenceArrivalId": data_point_sequence_arrival_id or 2,
        "timeZone": time_zone,
        "addressModel": {
            "address1": address1,
            "address2": address2,
            "cityOrTown": city,
            "stateOrProvince": state,
            "zipCode": zip_code,
            "country": country,
            "longitude": str(longitude),
            "latitude": str(latitude),
            "id": None,
            "enabled": None,
            "createdBy": None,
            "createdOn": None,
            "modifiedBy": None,
            "modifiedOn": None
        },
        "locationGroupIds": location_group_ids or [],
        "productIds": product_ids or [],
        "locationSegmentName": location_segment_name,
        "address1": address1,
        "address2": address2,
        "cityOrTown": city,
        "stateOrProvince": state,
        "zipCode": zip_code,
        "country": country,
        "latitude": latitude,
        "longitude": longitude
    }
